### ISSUE TITLE
Archive directory is in wrong place

### ISSUE THREAD

**Issue by php4umagento** [SecureTrading/PHP-Log#1]
https://github.com/SecureTrading/PHP-Log/blob/master/src/FileWriter.php#L41

is trying to create archive folder under vendor/securetrading/var/log/archive/ which will cause issues on systems where vendor folder is readonly

also I believe that this is not best location, f.e. for Magento it should be ROOT/var/log

**Comment by peter-barrow-ST** [comment]
The log writes to vendor/securetrading/var/log/ and vendor/securetrading/var/log/archive/ by default but this can be overwritten when constructing the logger.


Three samples are given below that set the log folder to /var/log/ and the log archive folder to /var/log/archive/: the samples differ depending on how the logger has been constructed.

### 1 - If using securetrading/ioc and stLog:

```
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$ioc =  \Securetrading\Ioc\Helper::instance()
     ->addVendorDirs(realpath(__DIR__ . '/vendor/securetrading/'))
     ->loadPackage('stLog')
     ->getIoc();

$log = $ioc->get('stLog', [
    'logFileName' => 'our_log_name',
    'logFilePath' => '/var/log/our_log_folder/',
    'logArchivePath' => '/var/log/our_log_folder/archive/',
]);

$log->info('test message');
```

### 2 - If using securetrading/ioc and stLog:

```
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$ioc = \Securetrading\Ioc\Helper::instance()
     ->addVendorDirs(realpath(__DIR__ . '/vendor/securetrading/'))
     ->loadPackage('stLog')
     ->getIoc();

$log = $ioc->get('\Securetrading\Log\FileWriter', [
    'logFileName' => 'our_log_name',
    'logFilePath' => '/var/log/our_log_folder/',
    'logArchivePath' => '/var/log/our_log_folder/archive/',
]);

$log->info('test message');
```

### 3 - If not using securetrading/ioc and stLog:

```
<?php

require_once(__DIR__ . '/vendor/autoload.php');

$log = new \Securetrading\Log\FileWriter(
    'our_log_name',
    '/var/log/our_log_folder/',
    '/var/log/our_log_folder/archive/'
);

$log->info('test message');
```

**Comment by php4umagento** [comment]
The actual logger is called in Securetrading\Stpp\JsonInterface::process() which we have no control over


`public function process($request) {
    $requestReference = 'NOREQREF';
    try {
      $translator = $this->_ioc->get('\Securetrading\Stpp\JsonInterface\Translator', array('config' => $this->_config));
      $converter = $this->_ioc->get('\Securetrading\Stpp\JsonInterface\Converter', array('config' => $this->_config, 'ioc' => $this->_ioc));
      $httpClient = $this->_ioc->get('\Securetrading\Stpp\JsonInterface\Http', array($this->_ioc, $this->_config));

      $request = $this->_verifyRequest($request);

      $requestReference = $request->getSingle('requestreference');
      $this->_getLog()->info("Starting request.");

      $jsonRequestString = $converter->encode($request);
      $httpResponseString = $httpClient->send($jsonRequestString, $requestReference, $this->_getUrl($request));
      $responseObject = $converter->decode($httpResponseString);
      
      $this->_verifyResult($responseObject, $requestReference);
    }`



and you have

`protected function _getLog() {
    return $this->_ioc->getSingleton('\Securetrading\Stpp\JsonInterface\Log');
  }`

**Comment by php4umagento** [comment]
Ok I solved it now
